# Generated by Django 2.1.3 on 2018-11-29 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(to='business.Category'),
        ),
        migrations.AddField(
            model_name='business',
            name='comment_business',
            field=models.ManyToManyField(through='business.CommentBusiness', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentbusiness',
            name='business',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='business.Business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentbusiness',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
