# Generated by Django 2.1.3 on 2018-12-01 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_promotion_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotion',
            new_name='Promo',
        ),
    ]
