# Generated by Django 2.1.3 on 2018-12-07 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0004_auto_20181130_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='commentbusiness',
            options={'verbose_name_plural': 'Comment Business'},
        ),
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='comment_business',
            field=models.ManyToManyField(related_name='comment_business', through='business.CommentBusiness', to=settings.AUTH_USER_MODEL),
        ),
    ]
